      - name: Deploy to EC2 and restart app
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/kasadara-kal-admin
            git pull origin main
            npm ci
            npm run build
            pm2 delete react-app || true
            pm2 serve dist 3000 --name react-app
          EOF
